services:

  kibana:
    restart: unless-stopped
    image: kibana:8.6.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  elasticsearch:
    restart: unless-stopped
    image: elasticsearch:8.6.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      
